# Generated by Django 4.2.25 on 2025-11-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nodes',
            new_name='Notes',
        ),
    ]
