# Generated by Django 4.2.25 on 2026-01-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_notes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
