# Generated by Django 4.2.25 on 2025-11-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank='draft', choices=[('draft', 'Draft'), ('prototypes', 'Prototypes'), ('development', 'Development'), ('review', 'Review')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created', models.DateField()),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
