# Generated by Django 4.2.25 on 2025-11-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Task',
        ),
    ]
